### ISSUE TITLE
install_conda.sh does not install mkl

### ISSUE THREAD

**Issue by jsoishi** [DedalusProject/dedalus_conda#4]
If mkl is selected, the script builds against netlib blas/lapack.

**Comment by kburns** [comment]
Not entirely sure, but according to https://github.com/conda/conda/issues/9981 and https://conda-forge.org/docs/maintainer/knowledge_base.html#blas, it looks like conda builds numpy against the generic netlib interface, but then picks up whatever blas has installed been installed by conda at runtime.  Not sure how to test if you're actually hitting MKL though...

**Comment by kburns** [comment]
On mac right now, selecting mkl for some reason pulls in clang-10 and fails with the associated problems. If I force clang-11 though, it seems to install and run ok.  Conda installs MKL, but numpy's show_config doesn't identify MKL specifically.

**Comment by kburns** [comment]
I did some timing tests with mkl vs openblas using conda on mac, and it does look like there's a difference, but it isn't huge.  On `scipy.linalg.eig` and `scipy.linalg.svd`, it looks like mkl is about 10-20% faster.

**Comment by kburns** [comment]
Looking again, the [conda-forge docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation) say the old `"blas=*=mkl"` syntax is still supported, and this still seems to work on mac, but I confirmed that it does fail on linux and you just end up with netlib, as you found.  I updated to the new `"libblas=*=*mkl"` syntax in https://github.com/DedalusProject/dedalus_conda/commit/a3b85d776c57fed1b704382cab10533ad4d0387c and it now seems to work correctly.
